### ISSUE TITLE
Load configuration from URL

### ISSUE THREAD

**Issue by cmaneu** [surfriderfoundationeurope/labelcv-web#32]
Load App configuration from `/config.json` instead of hard-coded values

**Comment by bertrandlalo** [comment]
https://github.com/surfriderfoundationeurope/labelcv-web/commit/c448aaacdb35133c3ad54b4bd94e1dbcf8c1e8c1

Is it ok like this @cmaneu ? 
Having `config.json` having key "url".

**Comment by bertrandlalo** [comment]
This should be better : https://github.com/surfriderfoundationeurope/labelcv-web/commit/2e5b84e201e365c8fd692eec3fd32e27b16038a0

One remaining issue though : the first request to fetch the image is made 'too late', so until we fiw it, to test the application, you should Skip the first time (since no image is fetched).
